[package]
name = "json_trace"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot  = "0.12.5"
serde        = { version = "1.0.228", features = ["derive", "rc"] }
serde_json   = "1.0.149"
erased-serde = "0.4.9"
log = "0.4.29"
env_logger = "0.11.8"
