[package]
name = "enum_utils"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

[dependencies]
quote = { version = "1.0.43", default-features = false }
syn   = { version = "2.0.114", features = ["full", "extra-traits"] }
